name: Deploy to Amazon ECS 

on: 
    workflow_dispatch:
    pull_request: 
        types: ['closed']
        branches: ['master']
    
permissions: 
    contents: read 
    actions: read 

jobs: 
    deploy:
        if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop'
        name: Deploy
        runs-on: ubuntu-20.04

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Echo 
              run: echo Github deployed
    notify-slack:
        needs: deploy
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop'
        steps: 
            - name: Run 
              run: echo NOTIFY SLACK