name: Generate Changelog

on:
    pull_request:
        branches:
            - main
        types: [opened, synchronize] # trigger on opened and sync
    workflow_dispatch:
        inputs:
            dry_run:
                description: 'Dry run (true/false)'
                required: false
                default: 'true'

permissions:
    contents: write

jobs:
    generate-changelogs:
        runs-on: ubuntu-latest

        steps:
            - name: Authenticate with GitHub App
              id: auth
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ secrets.APP_ID }}
                  private-key: ${{ secrets.APP_PRIVATE_KEY }}
            - uses: actions/checkout@v4
              with:
                  token: ${{ steps.auth.outputs.token }}

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: 📥 Install GitHub CLI
              run: sudo apt-get install -y gh

            - name: 🚀 Run release script
              run: |
                  if [ "${{ inputs.dry_run }}" = "true" ]; then
                    node release.js --dry-run
                  else
                    node release.js
                  fi
              env:
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  GITHUB_TOKEN: ${{ steps.auth.outputs.token }}

            - name: 📝 Commit & push changes
              if: ${{ inputs.dry_run != 'true' }}
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  # Make sure we're on the latest develop branch
                  git fetch origin
                  git checkout ${{ github.event.pull_request.head.ref }}
                  git pull origin ${{ github.event.pull_request.head.ref }}

                  # Run changelog script again just in case base changed
                  node release.js

                  # Commit only if there are changes
                  git add package.json version.txt CHANGELOG.md || echo "Nothing to add"
                  git diff --cached --quiet || (
                    git commit -m "chore: release version bump"
                    git push origin ${{ github.event.pull_request.head.ref }}
                  )
